# Example mcMMOIRC configuration
#
# This configuration file specifies tags for CraftIRC's
# configuration. CraftIRC's configuration file will need
# to be modified before mcMMOIRC will work correctly.
#
# Example CraftIRC configuration:
#   https://github.com/jgeboski/mcMMOIRC/blob/master/config.craftirc.yml

admin:
  tag: 'adminchat'
  prefix: '&3'
  suffix: '&r'

parties:
  - name: 'test'
    tag: 'testparty'
    prefix: '&3'
    suffix: '&r'
