name: mcMMOIRC
version: 0.2.0
description: Integrate the mcMMO chat system with CraftIRC
author: jgeboski
main: org.mcmmoirc.mcMMOIRC
depend: ['CraftIRC', 'mcMMO']

commands:
  mcmmoirc:
    description: mcMMOIRC main command
    usage: /<command> reload
    aliases: mirc

permissions:
  mcmmoirc.reload:
    description: Reload mcMMOIRC
    default: op
